version: "3"

services:
  zerotierbridge:
    container_name: zerotierbridge
    build: .
    restart: always
    devices:
      - /dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    volumes:
      - zt_config:/var/lib/zerotier-bridge
    environment:
      - ZT_NETWORKS=NETWORK_ID_1 NETWORK_ID_2 NETWORK_ID_3
      - ZT_BRIDGE=true
volumes:
  zt_config: