name: Publish Docker Image

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        id: registry_push
        uses: docker/login-action@v3
        with:
          registry: registry.dangerous.tech
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dangeroustech/zerotierbridge:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
