name: Generate SBOM

on:
  release:
    types: [created]

jobs:
  GenerateSBOM:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        id: sbom
        with:
          image: registry.dangerous.tech/dangeroustech/zerotierbridge:latest
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
